/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace FaceRecord {
      
    export type RecordStruct = {faceEncodingHash: BytesLike, matchPayloadHash: BytesLike, matchedUrl: string, matchSourceApi: string, ipfsCid: string, faceMatchDistance: BigNumberish, timestamp: BigNumberish, submittedBy: AddressLike}

    export type RecordStructOutput = [faceEncodingHash: string, matchPayloadHash: string, matchedUrl: string, matchSourceApi: string, ipfsCid: string, faceMatchDistance: bigint, timestamp: bigint, submittedBy: string] & {faceEncodingHash: string, matchPayloadHash: string, matchedUrl: string, matchSourceApi: string, ipfsCid: string, faceMatchDistance: bigint, timestamp: bigint, submittedBy: string }
  
    }

  export interface FaceRecordInterface extends Interface {
    getFunction(nameOrSignature: "addRecord" | "getRecord" | "totalRecords"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "RecordAdded"): EventFragment;

    encodeFunctionData(functionFragment: 'addRecord', values: [BytesLike, BytesLike, string, string, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRecord', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalRecords', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'addRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRecords', data: BytesLike): Result;
  }

  
    export namespace RecordAddedEvent {
      export type InputTuple = [recordId: BigNumberish, faceEncodingHash: BytesLike, matchedUrl: string, ipfsCid: string, timestamp: BigNumberish];
      export type OutputTuple = [recordId: bigint, faceEncodingHash: string, matchedUrl: string, ipfsCid: string, timestamp: bigint];
      export interface OutputObject {recordId: bigint, faceEncodingHash: string, matchedUrl: string, ipfsCid: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FaceRecord extends BaseContract {
    
    connect(runner?: ContractRunner | null): FaceRecord;
    waitForDeployment(): Promise<this>;

    interface: FaceRecordInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addRecord: TypedContractMethod<
      [faceEncodingHash: BytesLike, matchPayloadHash: BytesLike, matchedUrl: string, matchSourceApi: string, ipfsCid: string, faceMatchDistanceScaled: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    getRecord: TypedContractMethod<
      [recordId: BigNumberish, ],
      [FaceRecord.RecordStructOutput],
      'view'
    >
    

    
    totalRecords: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addRecord'): TypedContractMethod<
      [faceEncodingHash: BytesLike, matchPayloadHash: BytesLike, matchedUrl: string, matchSourceApi: string, ipfsCid: string, faceMatchDistanceScaled: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getRecord'): TypedContractMethod<
      [recordId: BigNumberish, ],
      [FaceRecord.RecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'totalRecords'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'RecordAdded'): TypedContractEvent<RecordAddedEvent.InputTuple, RecordAddedEvent.OutputTuple, RecordAddedEvent.OutputObject>;

    filters: {
      
      'RecordAdded(uint256,bytes32,string,string,uint256)': TypedContractEvent<RecordAddedEvent.InputTuple, RecordAddedEvent.OutputTuple, RecordAddedEvent.OutputObject>;
      RecordAdded: TypedContractEvent<RecordAddedEvent.InputTuple, RecordAddedEvent.OutputTuple, RecordAddedEvent.OutputObject>;
    
    };
  }