/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Counter__factory } from './Counter__factory.js';
export { FaceRecord__factory } from './FaceRecord__factory.js';